spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
        routes:
          - id: song-titles-route
            uri: lb://song-service
            predicates:
              - Path=/song-service/**
          - id: song-topics-route
            uri: lb://song-service
            predicates:
              - Path=/song-service/**
          - id: config-route
            uri: lb://config
            predicates:
              - Path=/config/**
          - id: discovery-route
            uri: lb://discovery
            predicates:
              - Path=/discovery/**
            filters:
              - RewritePath="/song-service-**/(?<segment>.*)",
                "/song-service-feign/${segment}"
        jwt:
          secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
#eureka:
#  client:
#    enabled: true
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: DEBUG