server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      import: config
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

logging:
  level:
    web: DEBUG